'use strict';

/**
 * Assembles the final README.md content string from all gathered data.
 */
function formatReadme({ pkg, structure, envVars, stack, outputFile }) {
  const name        = pkg?.name        || 'My Project';
  const description = pkg?.description || 'No description provided.';
  const version     = pkg?.version     || '1.0.0';
  const scripts     = pkg?.scripts     || {};
  const deps        = pkg?.dependencies    || {};
  const devDeps     = pkg?.devDependencies || {};

  const sections = [];

  // ── Title & Description ──────────────────────────────────────────────────
  sections.push(`# ${toTitleCase(name)}`);
  sections.push('');
  sections.push(`> ${description}`);
  sections.push('');

  if (version) {
    sections.push(`![version](https://img.shields.io/badge/version-${version}-blue.svg)`);
    sections.push('');
  }

  // ── Tech Stack ───────────────────────────────────────────────────────────
  sections.push('## 🛠 Tech Stack');
  sections.push('');
  if (stack.length > 0) {
    stack.forEach(({ name: techName }) => {
      sections.push(`- ${techName}`);
    });
  } else {
    sections.push('_No dependencies detected._');
  }
  sections.push('');

  // ── Project Structure ─────────────────────────────────────────────────────
  sections.push('## 📁 Project Structure');
  sections.push('');
  sections.push('```');
  sections.push(structure || '_Empty project_');
  sections.push('```');
  sections.push('');

  // ── Installation ──────────────────────────────────────────────────────────
  sections.push('## 🚀 Installation');
  sections.push('');
  sections.push('```bash');
  sections.push(`# 1. Clone the repository`);
  sections.push(`git clone <your-repo-url>`);
  sections.push(`cd ${name}`);
  sections.push('');
  sections.push('# 2. Install dependencies');
  sections.push('npm install');

  if (envVars.length > 0) {
    sections.push('');
    sections.push('# 3. Set up environment variables');
    sections.push('cp .env.example .env');
    sections.push('# Then fill in the values in .env');
  }

  sections.push('```');
  sections.push('');

  // ── Environment Variables ─────────────────────────────────────────────────
  if (envVars.length > 0) {
    sections.push('## 🔐 Environment Variables');
    sections.push('');
    sections.push('Copy `.env.example` to `.env` and fill in the following:');
    sections.push('');
    sections.push('| Variable | Description |');
    sections.push('|----------|-------------|');
    envVars.forEach((line) => {
      const [key, ...rest] = line.split('=');
      const example = rest.join('=').trim() || '—';
      sections.push(`| \`${key.trim()}\` | ${example} |`);
    });
    sections.push('');
  }

  // ── Scripts ───────────────────────────────────────────────────────────────
  if (Object.keys(scripts).length > 0) {
    sections.push('## 📜 Scripts');
    sections.push('');
    sections.push('| Script | Command |');
    sections.push('|--------|---------|');
    Object.entries(scripts).forEach(([scriptName, cmd]) => {
      sections.push(`| \`npm run ${scriptName}\` | \`${cmd}\` |`);
    });
    sections.push('');
  }

  // ── Dependencies ─────────────────────────────────────────────────────────
  const depList    = Object.entries(deps);
  const devDepList = Object.entries(devDeps);

  if (depList.length > 0 || devDepList.length > 0) {
    sections.push('## 📦 Dependencies');
    sections.push('');

    if (depList.length > 0) {
      sections.push('### Production');
      sections.push('');
      sections.push('| Package | Version |');
      sections.push('|---------|---------|');
      depList.forEach(([pkg, ver]) => {
        sections.push(`| \`${pkg}\` | ${ver} |`);
      });
      sections.push('');
    }

    if (devDepList.length > 0) {
      sections.push('### Development');
      sections.push('');
      sections.push('| Package | Version |');
      sections.push('|---------|---------|');
      devDepList.forEach(([pkg, ver]) => {
        sections.push(`| \`${pkg}\` | ${ver} |`);
      });
      sections.push('');
    }
  }

  // ── Footer ────────────────────────────────────────────────────────────────
  sections.push('---');
  sections.push('');
  sections.push(`_Generated by [readme-gen](https://github.com/your-org/readme-gen)_`);
  sections.push('');

  return sections.join('\n');
}

function toTitleCase(str) {
  return str
    .replace(/[-_]/g, ' ')
    .replace(/\w\S*/g, (txt) => txt.charAt(0).toUpperCase() + txt.slice(1));
}

module.exports = { formatReadme };
